apiVersion: v1
kind: ServiceAccount
metadata:
    name: cri-test
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cri-test
spec:
  template:
    metadata:
      labels:
        app: cri-test
      name: cri-test
    spec:
      serviceAccountName: cri-test
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      containers:
      - image: docker.io/lilic/scope-cri:latest 
        args:
          - "--container-runtime-endpoint=unix:///var/run/crio.sock"
        imagePullPolicy: Always
        name: cri-test
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: cri-endpoint
          mountPath: /var/run/crio.sock
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
      - name: cri-endpoint
        hostPath:
          path: /var/run/crio/crio.sock
          type: Socket
